config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [ :create,  :edit, :update, :show ] do
    patch 'created', on: :member
    patch 'running', on: :member
    patch 'paused', on: :member
    resources :participations, only: [ :edit, :update ]
    resources :answers, only: [ :create, :show ]
  end
  get "users/:id", to: "users#show", as: :user
  resources :participations, only: [ :new, :create, :show ]

  Rails.application.routes.draw do
    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/views/pages/home.html.erb
<div id="homepage" class="height-100 background-gradient" user-data-set="current_user.id">

  <div class="nav-item dropdown text-right w-100">
    <% if user_signed_in? %>
      <div class="user-icon"><%= @user.pseudo[0].capitalize %>

        <ul id="userMenu" class="user-menu" style="display: none">
          <li><%= link_to "Dashboard", user_path(@user), class: "nav-user-menu narrow" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-user-menu" %></li>
        </ul>

      </div>

    <% else %>

      <div id="homeMenu" class="homepage-menu" style="display: none">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%= link_to "Signup ", new_user_registration_path, class: "nav-link" %>
      </div>

    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="content padding-t-10">
  <% else %>
    <div class="content padding-b-15">
  <% end %>

    <div class="image">
      <%= image_tag "image.png", class: "logo-gt" %>
    </div>
    <h1>GUESS WHAT</h1>
    <p>SHARE MUSIC ANYWHERE</p>

  </div>


    <% if user_signed_in? %>
  <div class="text-center h-25">
    <div class="pb-5">
      <%= simple_form_for @game do |f| %>
        <%= f.submit "Crée une partie", class: "btn-home pb-10" %>
    </div>
    <% end %>
      <div>
        <%= link_to "REJOINS UNE PARTIE", new_participation_path , class: "btn-home2" %>
      </div>
    </div>
  <% end %>
</div>