config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [ :create,  :edit, :update, :show ] do
    patch 'created', on: :member
    patch 'running', on: :member
    patch 'paused', on: :member
    resources :participations, only: [ :edit, :update ]
    resources :answers, only: [ :create, :show ]
  end
  get "users/:id", to: "users#show", as: :user
  resources :participations, only: [ :new, :create, :show ]

  Rails.application.routes.draw do
    # Sidekiq Web UI, only for admins.
    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :playlist, optional: true
  has_many :participations
  has_many :participants, through: :participations, source: :user
  has_many :answers
  # has_many :tracks, through: :playlists
  enum status: [ :created, :running, :paused, :finished ]
  validates :user_id, presence: true
  validates :token, uniqueness: true
  before_validation :set_token
  after_initialize :set_defaults, unless: :persisted?

  NUMBER_OF_ROUNDS = 5

  def set_defaults
    self.total_score ||= 0
  end

  private

  def set_token
    if self.id.nil?
      self.token = SecureRandom.hex(3)
    end
    # set_token if Game.all.map{|game| game.token}.include?(self.token) # to check later / 20 06 20
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  # def new
  #   # raise # to check that action is no use
  #   @game = Game.new(user: current_user) if current_user
  # end

  def create
    # @game = policy_scope(Game.find(params[:id]))
    @game = Game.new(user: current_user, total_score: 0)
    authorize @game
    @game.status = :created
    @game.save
    redirect_to edit_game_path(@game)
  end

  def edit
    @game = Game.find(params[:id])
    @playlists = Playlist.all
    authorize @game
  end

  def update
    @game = Game.find(params[:id])
    @game.playlist_id = params[:playlist_id]
    new_playlist = Playlist.where(name:@game.playlist.name).last
    @game.playlist = new_playlist
    PlaylistJob.perform_later(@game.playlist.name)

    if @game.playlist_id != nil
        @game.save
        authorize @game
        redirect_to game_path(@game)
    else
        authorize @game
        redirect_to edit_game_path(@game)
    end
  end

  def show
    @game = Game.find(params[:id])
    @answer = Answer.new
    @participation = Participation.find_by(token: @game.token)
    authorize @game
    @user = @game.user # MJ
    # @partipants = @game.participants # player 2
    @playlist = @game.playlist
    @answers = @game.answers
    # test pour passage à la prochaine track
    @current_track = @game.playlist.tracks.where.not(id: @answers.where(status: true).pluck(:track_id)).first
    authorize @game
    if @current_track
      if @current_track.answers.empty? || @current_track.answers.last.status == true
        @answering_time = 0
      else
        @answering_time = @current_track.answers.last.answering_time
      end
    end

  end

  def created
    @game = Game.find(params[:id])
    @main_user = @game.user
  end

  def running
    @game = Game.find(params[:id])
    @answer = Answer.new
    @user = current_user
    @game.running!
    @playlist = @game.playlist
    if @game.participants.any?
      @answers = @game.answers
      @current_track = @game.playlist.tracks.where.not(id: @answers.where(status: true).pluck(:track_id)).first
      if @current_track.answers.empty? || @current_track.answers.last.status == true
        @answering_time = 0
      else
        @answering_time = @current_track.answers.last.answering_time
      end

      GameChannel.broadcast_to(
      @game,
      status: 'running',
      content: render_to_string(
        partial: "game_running",
        locals: {
          answering_time: @answering_time,
          current_track: @current_track,
          game: @game,
          answer: @answer
        }),
      navbar: render_to_string(
        partial: "navbar",
        locals: {
            user: @user,
            game_participants: @game_participants,
            playlist: @playlist
        })
      )

    end
    redirect_to game_path(@game)
    authorize @game
  end

  def paused
    @game = Game.find(params[:id])
    @answer = Answer.new()
    authorize @game
    @game.paused!
    # ajouté par Pierre pour broadcaster des valeurs !nil
    if @game.participants.any?
      @answers = @game.answers

      @current_track = @game.playlist.tracks.where.not(id: @answers.where(status: true).pluck(:track_id)).first
      if @current_track.answers.empty? || @current_track.answers.last.status == true
        @answering_time = 0
      else
        @answering_time = @current_track.answers.last.answering_time
      end
      GameChannel.broadcast_to(
        @game,
        status: 'paused',
        content: render_to_string(
          partial: "game_wait",
          locals: {
        current_track: @current_track,
        game: @game,
        answer: @answer,
        user: current_user
          }
          ),
        user: current_user
        )
    end
    redirect_to game_path(@game, current_time: params[:current_time])
  end


  private

  def game_params
    params.require(:game).permit(:status, :playlist_id, :total_score)
  end

end

app/views/games/_board.html.erb
<div id="board">
  <div id="song-counter" class="song-count d-flex justify-content-around align-items-center">
    <%= '<i class="fas fa-record-vinyl guessed"></i>'.html_safe * Answer.where(status:true).count %>
    <%= '<i class="fas fa-record-vinyl"></i>'.html_safe * (Game::NUMBER_OF_ROUNDS - Answer.where(status:true).count) %>
  </div>

  <ul id="player" class="list-inline d-flex align-items-center">
    <li class="d-none list-inline-item audio" data-time="<%= @answering_time %>">
        <%= audio_tag("#{@current_track.url_preview}", autoplay: true, controls: true, id:"song") %>
    </li>
  </ul>
</div>

app/views/games/_created.html.erb
<div class="top-container">
  <div class="welcome-top" id="answers" data-game-id="<%= @game.id %>">
    <% if @game.user == current_user %>
      <h4><%= @game.user.pseudo %>, invite tes potes à jouer avec toi !</h4>
      <br>
      <div class="token-card">
        <div class="avatar-key d-flex justify-content-around align-items-center">
          <i class="fas fa-key"></i>
        </div>
        <h6 class="mt-3">Voici le code pour rejoindre ta partie : </h6>
        <strong><h2 class="mt-3 "><%= @game.token %></h2></strong>
      </div>
      <br>
      <br>
  </div>
      <%= link_to running_game_path(@game), method: :patch do %>
      <div class="play-btn mt-5"></div>
    <% end %>
    <% else %>
      <h3>Tu as rejoint la partie de <%= @game.user.pseudo %> !</h3>
  <% end%>
  </div>
</div>

app/views/games/_game_created.html.erb
<div class="top-container">

  <div class="welcome-top" > <!--id="answers" data-game-id="<%= @game.id %>" -->
    <% if @game.user == current_user %>
      <h3><%= @game.user.pseudo %>,</h3>
      <h3>invite tes potes à jouer avec toi !</h3>
      <br>
      <br>
      <div class="token-card">
        <div class="avatar-key d-flex justify-content-around align-items-center">
          <i class="fas fa-key"></i>
        </div>
        <br>
        <strong><h2 class="mt-3 "><%= @game.token %></h2></strong>
      </div>
      <br>
      <br>

      <div id="answers" data-game-id="<%= @game.id %>">

      </div>
      <div class="mt-5 pb-3">
        <%= link_to running_game_path(@game), method: :patch do %>
          <div class="play-btn "></div>
        <% end %>
      </div>
    <% else %>
      <div class="participant-created">
        <h2>Tu as rejoint la partie de <strong><%= @game.user.pseudo %></strong> !</h2>
        <br>
        <h4>Prépare toi à tout donner</h4>
        <br>
        <i class="fas fa-music fa-2x"></i>
      </div>
    <% end%>
  </div>
</div>

app/views/games/_game_finished.html.erb
<div id="dashboard" class="background-gradient force-height">
  <div class="d-flex justify-content-between w-100 pb-3">
    <div>
      <%= link_to root_path do %>
      <%= image_tag "logo-icon.png"%>
      <% end %>
    </div>
    <h3><%= @user.pseudo %></h3>

    <div class="user-icon"><%= @user.pseudo[0].capitalize %>
      <ul id="userMenu" class="user-menu" style="display: none">
        <li><%= link_to "Dashboard", user_path(@user), class: "nav-user-menu narrow" %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-user-menu" %></li>
      </ul>
    </div>
  </div>

  <div class="dashboard-container text-center">
    <% mj_game_good = @game.user.answers.where("status = ? AND game_id = ?", true, @game.id) %>
    <% total_score = 0 %>
    <% mj_game_good.each do |answer| %>
      <% total_score += answer.score %>
    <% end %>
    <% @game.total_score = total_score %>
    <% @game.save %>

  <% if @participation %>
    <% player2_game_good = @game.participants[0].answers.where("status = ? AND game_id = ?", true, @game.id) %>
    <% total_player2 = 0 %>
    <% player2_game_good.each do |answer| %>
      <% total_player2 += answer.score %>
    <% end %>
    <% @participation.total_score = total_player2 %>
    <% @participation.save %>

    <% if @game.total_score >= @participation.total_score %>
      <i class="fas fa-crown fa-4x"></i>
      <br>
      <span class="particletext confetti"> <%= @game.user.pseudo %></span>
      <p><%= @game.total_score %> points</p>
    <% else %>
      <i class="fas fa-crown fa-4x"></i>
      <br>
      <span class="particletext confetti"> <%= @game.participants[0].pseudo %></span>
      <p><%= @participation.total_score %> points</p>
    <% end %>
  <% else %>
    <i class="fas fa-crown fa-4x"></i>
      <br>
      <span class="particletext confetti"> <%= @game.user.pseudo %></span>
      <p><%= @game.total_score %> points</p>
  <% end %>
</div>

    <!-- <div class="album-photo" style="background-image: url(<%#= result[0].album.images[0]["url"] %>)" >
    </div> -->

<!-- ---------------- -->

<div id="playlist-display" class="mx-2" >
  <% RSpotify.authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"]) %>
  <% @game.playlist.tracks.each do |track| %>
    <% result = RSpotify::Track.search("#{track.title}") %>
    <div class="card-song">
      <img src="<%= result[0].album.images[0]["url"] %>"/>
    <div class="card-song-infos">
      <h2><%= track.title %></h2>
      <p><%= track.artist %></p>
    </div>
    <div class="result text-right">
      <p><%#= User.last.pseudo %></p>
      <p class="points">
        <!-- AFFICHAGE DES SCORES (LA HAUT C'EST LE CALCUL DU SCORE TOTAL) -->
        <% guess_track = track.answers.where(status:true) %>
        <% game_guess_track = guess_track.where(game_id:@game.id) %>
        <% game_guess_track.each do |answer| %>
          <div class="user-result <%= answer.user == current_user ? "green" : ""%>" data-user="<%= answer.user.id  %>">
            <% if answer.user.pseudo == "Ghost" %>
              <p> - </p>
            <% else %>
              <p> <%= answer.user.pseudo %></p>
                <%= answer.score %>
            <% end %>
          </div>
        <% end %> <!-- fin de |answer| do -->
      </p>
      </div>
    <% link = result[0].album.external_urls["spotify"] %>
    <%= link_to "#{link}", target: :_blank do %>
      <i class="fab fa-spotify spotify"></i>
    <% end %>
   </div>
  <% end %>
</div>

<!-- bouton rejouer -->
<div class="replay">
  <div class="text-center mt-5">
    <% @game = Game.new(user: current_user) %>
    <%= simple_form_for @game do |f| %>
      <%= f.submit "Rejouer", class: "btn-home" %>
    <% end %>
  </div>
</div>

</div>

app/views/games/_game_paused.html.erb
<div class='display-container'>
  <div class="load">
    <i class="fa fa-microphone fa-3x"></i>
  </div>

  <div class="d-none form-container text-center">
    <%= simple_form_for [ @game, @answer ] do |f| %>
      <%= f.input :content, autofocus: true, label: false%>
      <%= f.hidden_field :track, value: @current_track.id %>
      <%= f.hidden_field :answering_time, value: params[:current_time] %>
      <%= f.submit "Réponse ?", class: 'btn btn-flat', id:"answer"%>
    <% end %>

    <div class="speechtotext-container">
      <i class="fa fa-microphone speechtotext"></i>
    </div>
  </div>
</div>
<!-- zone de secours pour recharger la page en cas d'echec d'enregistrement -->
<a href="#" onClick="window.location.reload();"><div id='refresh'></div></a>

app/views/games/_game_running.html.erb
<ul class="list-inline d-flex align-items-center">
  <!--          creer une data-audio-id = user.id -->
  <li class="d-none list-inline-item audio" data-time="<%= @answering_time %>">
    <%= audio_tag("#{@current_track.url_preview}", autoplay: false, controls: true, id:"song") %>
  </li>
</ul>

<div class="buzzer-content">
  <!-- creer une variable idBuzzer = 'buzz' + user.id -->
  <div class="consigne text-center">
    <h3 id="consigne">Touche pour donner <br> <br> ta réponse</h3>
  </div>

  <%= link_to paused_game_path(@game), method: :patch, id:"buzz" do %>

  <figure class="profile">
    <%= image_tag "image.png", class: "logo-show", id:"buzz-img"%>
  </figure>
  <% end %>
  <div class="countdown d-flex justify-content-center align-items-center" id="countdown">
    <p class="d-block" id="3">3</p>
    <p class="d-none" id="2">2</p>
    <p class="d-none" id="1">1</p>
  </div>

</div>

<div class="d-none ghost" data-answer="<%= @current_track.artist %>">
  <%= simple_form_for [ @game, @answer ], html: { id: :ghost_new_answer } do |f| %>
    <%= f.input :content, autofocus: true, label: false, input_html: { id: 'ghost_answer_content' }%>
    <%= f.hidden_field :track, value: @current_track.id %>
    <%= f.submit "Réponse ?", class: 'btn btn-flat', id:"ghost_answer"%>
  <% end %>
</div>

app/views/games/_game_wait.html.erb
<div id="message-modal">
  <div class="form-modal">
    <p> Ton adversaire a été plus rapide que toi 🚀 il donne une réponse... </p>
  </div>
</div>

app/views/games/_navbar.html.erb
<div class="navbar-game d-flex justify-content-around align items-center">

  <div class="home-game">
    <%= link_to root_path do %>
      <i class="fas fa-home"></i>
    <% end %>
  </div>

  <div class="song-count d-flex justify-content-around align-items-center">
    <%= '<i class="fas fa-circle icon guessed flashit"></i>'.html_safe * @game.answers.where(status:true).count %>
    <%= '<i class="fas fa-circle icon"></i>'.html_safe * (Game::NUMBER_OF_ROUNDS - @game.answers.where(status:true).count) %>
  </div>

  <!-- notif good answers -->
  <div class="d-flex justify-content-around align-items-center players-all">
    <div class="d-flex justify-content-center align-items-center">
      <div class="players"><%= @game.user.pseudo.chars.first.capitalize %>
      </div>
    </div>
    <% if @game.participants[0] %>
      <div class="players"><%= @game.participants[0].pseudo.chars.first.capitalize %>
      </div>
    <% end %>
  </div>
  <!-- fin notif good answers -->
</div>

<p class="playlist-name"><%= @playlist.name %></p>

app/views/games/edit.html.erb
<div id="playlists" class="background-gradient height-100">
  <!--<div class="container">-->
  <div class="d-flex flex-column align-items-center justify-content-between w-100">
    <div class="d-flex justify-content-left mb-3 w-100">
      <div>
        <%= link_to root_path do %>
        <%= image_tag "logo-icon.png"%>
        <% end %>
      </div>


    </div>

    <div class="edit-title text-center">
      <p>Sélectionne ta playlist</p>
    </div>

    <%= simple_form_for @game do |f| %>
      <div class="h-70">

        <div class="playlist_grid">
          <% @playlists.first(6).each do |playlist| %>
            <div class="playlist_card playlist_image" style="background-image: linear-gradient(rgba(0,0,255,0.15), rgba(0,0,100,0.4)), url(<%= asset_path playlist.picture %>)"  >
              <%= radio_button_tag 'playlist_id', playlist.id, false, class: "d-none" %>
              <%= label_tag "playlist_id_#{playlist.id}", playlist.name %>
            </div>
          <% end %>
        </div>

        <div class="playlist_btn">
          <%= f.submit "C'EST PARTI !", class: "btn-home" %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<head>
  <meta charset="utf-8">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<div class="game-container" style="background-image: linear-gradient(to right top, #df2866, #d8377f, #cc4794, #bc56a6, #aa63b3);">
  <div id="game-container" data-game-id="<%= @game.id %>" data-user-id="<%= current_user.id %>">

    <% if @game.paused? %>
      <%  @user = current_user %>
      <%= render 'game_paused',
        user: @user %>
    <% end %>

    <% if @game.created? %>
      <div class="show-created-html" id="game-created-html">
        <%= render 'game_created' %>
      </div>
    <% end %>

    <% if @game.running? && @current_track %>
      <div id="navbar">
        <%= render 'games/navbar',
          user: @user,
          game_participants: @game_participants,
          playlist: @playlist %>
      </div>

      <div id="running-html">
        <%= render 'game_running',
          answering_time: @answering_time,
          current_track: @current_track,
          game: @game %>

        <% if @game.answers.any? %>
            <% if @game.answers.last.user.pseudo == "Ghost" %>
              <% ghost_answers = "#{@game.answers.last.track.artist}, tu connais pas?", "Dommage... c'était #{@game.answers.last.track.title} de #{@game.answers.last.track.artist}"%>
                <div class="speech-bubble-bad-answer animated">
                <i class="far fa-times-circle fa-3x"></i>
                <p><%= ghost_answers.sample %></p>
              </div>
            <% elsif @game.answers.last.status == true %>
              <% good_answers = ["Bien joué petit génie de la zik 🕺", "Yes ! #{@game.answers.last.track.artist}, moi aussi j'adore 😍", "Yes ! Je te veux dans ma team !"] %>
              <div class="speech-bubble-good-answer animated">
                <i class="far fa-check-circle fa-3x"></i>
                <p><%= good_answers.sample %></p>
              </div>
            <% else %>
              <% bad_answers = ["Même ma petite soeur connaît ça ! 😔", "#{@game.answers.last.content} ?? Sérieusement... 🙄", "#{@game.playlist.name}, c'est définitivement pas ton truc"] %>
              <div class="speech-bubble-bad-answer animated">
                <i class="far fa-times-circle fa-3x"></i>
                <p><%= bad_answers.sample %></p>
              </div>
            <% end %>
        <% end %>
          <!-- fin de la section mise dans partial par Victor -->
      </div>
    <% end %> <!-- end du if game.running? -->

    <% if @game.finished? %>
      <div id="game-finished" style="background-image: linear-gradient(to right top, #df2866, #d8377f, #cc4794, #bc56a6, #aa63b3);">
        <!-- debut de la section a mettre dans partial-finished -->
        <!-- game paused - formulaire de réponse -->
        <%= render 'game_finished',
          status: 'finished',
          current_track: @current_track,
          game: @game %>

          <!-- fin de la section a mettre dans partial game-finished -->
      </div>
    <% end %>

  <!-- -----------------------  -->
    <%# end %>
  </div> <!-- div fermante du container -->
</div>

app/views/games/tmp.html.erb
tmp.html.erb

  <h1>test</h1>
    <%= simple_form_for [ @game] do |f| %>
        <%= f.input :playlist, as: :radio_buttons, collection: @playlists %>
      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>